/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see https://opensource.org/licenses/ms-pl for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Client.Extensibility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Client.Extensibility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the About dialog.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutDisplayName {
            get {
                return ResourceManager.GetString("AboutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an attachment to the feature.
        /// </summary>
        internal static string AddAttachmentsToolDescription {
            get {
                return ResourceManager.GetString("AddAttachmentsToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment.
        /// </summary>
        internal static string AddAttachmentsToolDisplayName {
            get {
                return ResourceManager.GetString("AddAttachmentsToolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a GeoRSS feed to the map.
        /// </summary>
        internal static string AddGeoRssFeedDescription {
            get {
                return ResourceManager.GetString("AddGeoRssFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GeoRSS.
        /// </summary>
        internal static string AddGeoRssFeedDisplayName {
            get {
                return ResourceManager.GetString("AddGeoRssFeedDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Heat Map to the map.
        /// </summary>
        internal static string AddHeatMapDescription {
            get {
                return ResourceManager.GetString("AddHeatMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Heat Map.
        /// </summary>
        internal static string AddHeatMapDisplayName {
            get {
                return ResourceManager.GetString("AddHeatMapDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a basemap for your map.
        /// </summary>
        internal static string BaseMapGalleryDescription {
            get {
                return ResourceManager.GetString("BaseMapGalleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Basemap.
        /// </summary>
        internal static string BaseMapGalleryDisplayName {
            get {
                return ResourceManager.GetString("BaseMapGalleryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data to the map by browsing to an ArcGIS Server endpoint .
        /// </summary>
        internal static string BrowseDescription {
            get {
                return ResourceManager.GetString("BrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseDisplayName {
            get {
                return ResourceManager.GetString("BrowseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string CategoryApplication {
            get {
                return ResourceManager.GetString("CategoryApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Table.
        /// </summary>
        internal static string CategoryAttributeTable {
            get {
                return ResourceManager.GetString("CategoryAttributeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string CategoryConfigure {
            get {
                return ResourceManager.GetString("CategoryConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string CategoryEditing {
            get {
                return ResourceManager.GetString("CategoryEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing.
        /// </summary>
        internal static string CategoryGeoprocessing {
            get {
                return ResourceManager.GetString("CategoryGeoprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string CategoryLayer {
            get {
                return ResourceManager.GetString("CategoryLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string CategoryMap {
            get {
                return ResourceManager.GetString("CategoryMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Events.
        /// </summary>
        internal static string CategoryMouseEvents {
            get {
                return ResourceManager.GetString("CategoryMouseEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup.
        /// </summary>
        internal static string CategoryPopup {
            get {
                return ResourceManager.GetString("CategoryPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string CategorySelection {
            get {
                return ResourceManager.GetString("CategorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbology.
        /// </summary>
        internal static string CategorySymbology {
            get {
                return ResourceManager.GetString("CategorySymbology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string CategoryTheme {
            get {
                return ResourceManager.GetString("CategoryTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the background for a theme.
        /// </summary>
        internal static string ChangeThemeBackgroundDescription {
            get {
                return ResourceManager.GetString("ChangeThemeBackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme Background.
        /// </summary>
        internal static string ChangeThemeBackgroundDisplayName {
            get {
                return ResourceManager.GetString("ChangeThemeBackgroundDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the selection from the current layer.
        /// </summary>
        internal static string ClearSelectionDescription {
            get {
                return ResourceManager.GetString("ClearSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearSelectionDisplayName {
            get {
                return ResourceManager.GetString("ClearSelectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the appearance and behavior of the selected layer.
        /// </summary>
        internal static string ConfigureLayerDescription {
            get {
                return ResourceManager.GetString("ConfigureLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Layer.
        /// </summary>
        internal static string ConfigureLayerDisplayName {
            get {
                return ResourceManager.GetString("ConfigureLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows configuration of the renderer for the current layer.
        /// </summary>
        internal static string ConfigureLayerRendererDescription {
            get {
                return ResourceManager.GetString("ConfigureLayerRendererDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure symbology.
        /// </summary>
        internal static string ConfigureLayerRendererDisplayName {
            get {
                return ResourceManager.GetString("ConfigureLayerRendererDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows configuration of the selected layer.
        /// </summary>
        internal static string ConfigureSelectedLayerDescription {
            get {
                return ResourceManager.GetString("ConfigureSelectedLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure layer.
        /// </summary>
        internal static string ConfigureSelectedLayerDisplayName {
            get {
                return ResourceManager.GetString("ConfigureSelectedLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the feature from the layer.
        /// </summary>
        internal static string DeleteGraphicToolDescription {
            get {
                return ResourceManager.GetString("DeleteGraphicToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Feature.
        /// </summary>
        internal static string DeleteGraphicToolDisplayName {
            get {
                return ResourceManager.GetString("DeleteGraphicToolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected layer from the map.
        /// </summary>
        internal static string DeleteLayerDescription {
            get {
                return ResourceManager.GetString("DeleteLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Layer.
        /// </summary>
        internal static string DeleteLayerDisplayName {
            get {
                return ResourceManager.GetString("DeleteLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the feature&apos;s geometry.
        /// </summary>
        internal static string EditShapeToolDescription {
            get {
                return ResourceManager.GetString("EditShapeToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Shape.
        /// </summary>
        internal static string EditShapeToolDisplayName {
            get {
                return ResourceManager.GetString("EditShapeToolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the feature&apos;s attribute values.
        /// </summary>
        internal static string EditValuesToolDescription {
            get {
                return ResourceManager.GetString("EditValuesToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Values.
        /// </summary>
        internal static string EditValuesToolDisplayName {
            get {
                return ResourceManager.GetString("EditValuesToolDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Application Context for this application.
        /// </summary>
        internal static string ExceptionNoValidApplicationContextForApplication {
            get {
                return ResourceManager.GetString("ExceptionNoValidApplicationContextForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the attrbutes of the selected features in the curent layer to a CSV file.
        /// </summary>
        internal static string ExportSelectionDescription {
            get {
                return ResourceManager.GetString("ExportSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selection.
        /// </summary>
        internal static string ExportSelectionDisplayName {
            get {
                return ResourceManager.GetString("ExportSelectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show records for the features within the current map extent.
        /// </summary>
        internal static string FilterByMapExtentDescription {
            get {
                return ResourceManager.GetString("FilterByMapExtentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Map Extent.
        /// </summary>
        internal static string FilterByMapExtentName {
            get {
                return ResourceManager.GetString("FilterByMapExtentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Show All.
        /// </summary>
        internal static string FilterBySelectionAll {
            get {
                return ResourceManager.GetString("FilterBySelectionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table will display features selected and not selected.
        /// </summary>
        internal static string FilterBySelectionAllDescription {
            get {
                return ResourceManager.GetString("FilterBySelectionAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Show Not Selected.
        /// </summary>
        internal static string FilterBySelectionNotSelected {
            get {
                return ResourceManager.GetString("FilterBySelectionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters Table to show only features not currently selected..
        /// </summary>
        internal static string FilterBySelectionNotSelectedDescription {
            get {
                return ResourceManager.GetString("FilterBySelectionNotSelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Show Selected.
        /// </summary>
        internal static string FilterBySelectionSelected {
            get {
                return ResourceManager.GetString("FilterBySelectionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters Table to show only features that are selected..
        /// </summary>
        internal static string FilterBySelectionSelectedDescription {
            get {
                return ResourceManager.GetString("FilterBySelectionSelectedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the features in the selected layer based on an attribute query.
        /// </summary>
        internal static string FilterLayerDescription {
            get {
                return ResourceManager.GetString("FilterLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Layer.
        /// </summary>
        internal static string FilterLayerDisplayName {
            get {
                return ResourceManager.GetString("FilterLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find features near the current selection.
        /// </summary>
        internal static string FindNearbyDescription {
            get {
                return ResourceManager.GetString("FindNearbyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Nearby.
        /// </summary>
        internal static string FindNearbyDisplayName {
            get {
                return ResourceManager.GetString("FindNearbyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool that uses an ArcGIS Server Geoprocessing Service.
        /// </summary>
        internal static string GeoprocessingDescription {
            get {
                return ResourceManager.GetString("GeoprocessingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing.
        /// </summary>
        internal static string GeoprocessingDisplayName {
            get {
                return ResourceManager.GetString("GeoprocessingDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to the selected layer.
        /// </summary>
        internal static string GoToLayerDescription {
            get {
                return ResourceManager.GetString("GoToLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Layer.
        /// </summary>
        internal static string GoToLayerDisplayName {
            get {
                return ResourceManager.GetString("GoToLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Behavior.
        /// </summary>
        internal static string IdentifyBehaviorDisplayName {
            get {
                return ResourceManager.GetString("IdentifyBehaviorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the layer&apos;s display order one position closer to the top of the map.
        /// </summary>
        internal static string MoveLayerDownDescription {
            get {
                return ResourceManager.GetString("MoveLayerDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveLayerDownDisplayName {
            get {
                return ResourceManager.GetString("MoveLayerDownDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the layer&apos;s display order one position closer to the bottom of the map.
        /// </summary>
        internal static string MoveLayerUpDescription {
            get {
                return ResourceManager.GetString("MoveLayerUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveLayerUpDisplayName {
            get {
                return ResourceManager.GetString("MoveLayerUpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigates to the help system.
        /// </summary>
        internal static string NavigateToHelpLinkDescription {
            get {
                return ResourceManager.GetString("NavigateToHelpLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to help link.
        /// </summary>
        internal static string NavigateToHelpLinkDisplayName {
            get {
                return ResourceManager.GetString("NavigateToHelpLinkDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the map.
        /// </summary>
        internal static string PrintDescription {
            get {
                return ResourceManager.GetString("PrintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string PrintDisplayName {
            get {
                return ResourceManager.GetString("PrintDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the selected layer.
        /// </summary>
        internal static string RefreshLayerDescription {
            get {
                return ResourceManager.GetString("RefreshLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Layer.
        /// </summary>
        internal static string RefreshLayerDisplayName {
            get {
                return ResourceManager.GetString("RefreshLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the selected layer.
        /// </summary>
        internal static string RenameLayerDescription {
            get {
                return ResourceManager.GetString("RenameLayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Layer.
        /// </summary>
        internal static string RenameLayerDisplayName {
            get {
                return ResourceManager.GetString("RenameLayerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the colors used by the map to the default.
        /// </summary>
        internal static string RestoreDefaultThemeDescription {
            get {
                return ResourceManager.GetString("RestoreDefaultThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Theme.
        /// </summary>
        internal static string RestoreDefaultThemeDisplayName {
            get {
                return ResourceManager.GetString("RestoreDefaultThemeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the features in the current layer.
        /// </summary>
        internal static string SelectAllDescription {
            get {
                return ResourceManager.GetString("SelectAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAllDisplayName {
            get {
                return ResourceManager.GetString("SelectAllDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features by drawing a box around them in the map.
        /// </summary>
        internal static string SelectByDrawDescription {
            get {
                return ResourceManager.GetString("SelectByDrawDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectByDrawDisplayName {
            get {
                return ResourceManager.GetString("SelectByDrawDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string SelectedIndexOfTotal {
            get {
                return ResourceManager.GetString("SelectedIndexOfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the service endpoint for the selected layer.
        /// </summary>
        internal static string ServiceDetailsDescription {
            get {
                return ResourceManager.GetString("ServiceDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        internal static string ServiceDetailsDisplayName {
            get {
                return ResourceManager.GetString("ServiceDetailsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays coordinates as the mouse hovers over the map.
        /// </summary>
        internal static string ShowMapCoordinatesDescription {
            get {
                return ResourceManager.GetString("ShowMapCoordinatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map Coordinates.
        /// </summary>
        internal static string ShowMapCoordinatesDisplayName {
            get {
                return ResourceManager.GetString("ShowMapCoordinatesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a dialog that demonstrates how theme colors appear when applied to different components of the map.
        /// </summary>
        internal static string ShowPreviewControlDescription {
            get {
                return ResourceManager.GetString("ShowPreviewControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Theme.
        /// </summary>
        internal static string ShowPreviewControlDisplayName {
            get {
                return ResourceManager.GetString("ShowPreviewControlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ArcGIS Server, SharePoint, Spatial Data Server, or GeoRSS data to your map.
        /// </summary>
        internal static string ToggleAddContentDescription {
            get {
                return ResourceManager.GetString("ToggleAddContentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Content.
        /// </summary>
        internal static string ToggleAddContentDisplayName {
            get {
                return ResourceManager.GetString("ToggleAddContentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the editing tools.
        /// </summary>
        internal static string ToggleEditDescription {
            get {
                return ResourceManager.GetString("ToggleEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string ToggleEditDisplayName {
            get {
                return ResourceManager.GetString("ToggleEditDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the map in full screen mode.
        /// </summary>
        internal static string ToggleFullScreenDescription {
            get {
                return ResourceManager.GetString("ToggleFullScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string ToggleFullScreenDisplayName {
            get {
                return ResourceManager.GetString("ToggleFullScreenDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Map Contents panel to view the map&apos;s layers.
        /// </summary>
        internal static string ToggleMapContentsDescription {
            get {
                return ResourceManager.GetString("ToggleMapContentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Contents.
        /// </summary>
        internal static string ToggleMapContentsDisplayName {
            get {
                return ResourceManager.GetString("ToggleMapContentsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for places or ArcGIS Server services.
        /// </summary>
        internal static string ToggleSearchDescription {
            get {
                return ResourceManager.GetString("ToggleSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ToggleSearchDisplayName {
            get {
                return ResourceManager.GetString("ToggleSearchDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the attribute table for the selected layer.
        /// </summary>
        internal static string ToggleTableDescription {
            get {
                return ResourceManager.GetString("ToggleTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Table.
        /// </summary>
        internal static string ToggleTableDisplayName {
            get {
                return ResourceManager.GetString("ToggleTableDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to the selected features in the current layer.
        /// </summary>
        internal static string ZoomToSelectionDescription {
            get {
                return ResourceManager.GetString("ZoomToSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom To.
        /// </summary>
        internal static string ZoomToSelectionDisplayName {
            get {
                return ResourceManager.GetString("ZoomToSelectionDisplayName", resourceCulture);
            }
        }
    }
}
