/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see https://opensource.org/licenses/ms-pl for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Mapping.Controls.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Mapping.Controls.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Selection.
        /// </summary>
        internal static string AddToSelection {
            get {
                return ResourceManager.GetString("AddToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Editing Tools....
        /// </summary>
        internal static string AdvancedOptionsHeader {
            get {
                return ResourceManager.GetString("AdvancedOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Advanced Tools.
        /// </summary>
        internal static string AdvancedOptionsHeaderHide {
            get {
                return ResourceManager.GetString("AdvancedOptionsHeaderHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display default templates when no other templates exist.
        /// </summary>
        internal static string AlwaysDisplayDefaultTemplates {
            get {
                return ResourceManager.GetString("AlwaysDisplayDefaultTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AttachmentEditorClose {
            get {
                return ResourceManager.GetString("AttachmentEditorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Attachment Editor.
        /// </summary>
        internal static string AttachmentEditorConfigHeader {
            get {
                return ResourceManager.GetString("AttachmentEditorConfigHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for uploading, downloading, and deleting of files associated with graphic features in a FeatureLayer.
        /// </summary>
        internal static string AttachmentEditorDescription {
            get {
                return ResourceManager.GetString("AttachmentEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Document.
        /// </summary>
        internal static string AttachmentEditorDisplayName {
            get {
                return ResourceManager.GetString("AttachmentEditorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Index:.
        /// </summary>
        internal static string AttachmentEditorFilterIndexPrompt {
            get {
                return ResourceManager.GetString("AttachmentEditorFilterIndexPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        internal static string AttachmentEditorFilterPrompt {
            get {
                return ResourceManager.GetString("AttachmentEditorFilterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Editor.
        /// </summary>
        internal static string AttachmentEditorHeader {
            get {
                return ResourceManager.GetString("AttachmentEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Height:.
        /// </summary>
        internal static string AttachmentEditorHeightPrompt {
            get {
                return ResourceManager.GetString("AttachmentEditorHeightPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple attachments to be uploaded at once.
        /// </summary>
        internal static string AttachmentEditorMultiSelectPrompt {
            get {
                return ResourceManager.GetString("AttachmentEditorMultiSelectPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Width:.
        /// </summary>
        internal static string AttachmentEditorWidthPrompt {
            get {
                return ResourceManager.GetString("AttachmentEditorWidthPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap polygons to nearby features.
        /// </summary>
        internal static string AutoComplete {
            get {
                return ResourceManager.GetString("AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autocomplete.
        /// </summary>
        internal static string AutocompleteTool {
            get {
                return ResourceManager.GetString("AutocompleteTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save edits.
        /// </summary>
        internal static string AutoSaveEditChanges {
            get {
                return ResourceManager.GetString("AutoSaveEditChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically select features when necessary - used by Cut, Reshape, Union, and AutoComplete tools.
        /// </summary>
        internal static string AutoSelect {
            get {
                return ResourceManager.GetString("AutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string ClearSelection {
            get {
                return ResourceManager.GetString("ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Tool.
        /// </summary>
        internal static string ClearTool {
            get {
                return ResourceManager.GetString("ClearTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep advanced editing tools active until a different tool is selected.
        /// </summary>
        internal static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit all feature layers.
        /// </summary>
        internal static string DefaultLayerIds {
            get {
                return ResourceManager.GetString("DefaultLayerIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Clustering.
        /// </summary>
        internal static string DisableClustering {
            get {
                return ResourceManager.GetString("DisableClustering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer editing is not allowed for clustered layers. Would you like to disable clustering now?.
        /// </summary>
        internal static string DisableClusteringPrompt {
            get {
                return ResourceManager.GetString("DisableClusteringPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow editing shapes.
        /// </summary>
        internal static string EditingShapesEnabled {
            get {
                return ResourceManager.GetString("EditingShapesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Modes:.
        /// </summary>
        internal static string EditModes {
            get {
                return ResourceManager.GetString("EditModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Graphic Operations:.
        /// </summary>
        internal static string EditOperations {
            get {
                return ResourceManager.GetString("EditOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose editing options.
        /// </summary>
        internal static string EditorOptionsHeader {
            get {
                return ResourceManager.GetString("EditorOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Editing.
        /// </summary>
        internal static string EditorWidgetConfiguration {
            get {
                return ResourceManager.GetString("EditorWidgetConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shape.
        /// </summary>
        internal static string EditShape {
            get {
                return ResourceManager.GetString("EditShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Toolbar available with Add Features.
        /// </summary>
        internal static string EditToolbarWithAddFeatures {
            get {
                return ResourceManager.GetString("EditToolbarWithAddFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit values.
        /// </summary>
        internal static string EditValues {
            get {
                return ResourceManager.GetString("EditValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex editing.
        /// </summary>
        internal static string EditVerticesEnabled {
            get {
                return ResourceManager.GetString("EditVerticesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freehand.
        /// </summary>
        internal static string Freehand {
            get {
                return ResourceManager.GetString("Freehand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain the aspect ratio of geometries.
        /// </summary>
        internal static string MaintainAspectRatio {
            get {
                return ResourceManager.GetString("MaintainAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving.
        /// </summary>
        internal static string MoveEnabled {
            get {
                return ResourceManager.GetString("MoveEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Selection.
        /// </summary>
        internal static string RemoveFromSelection {
            get {
                return ResourceManager.GetString("RemoveFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshape.
        /// </summary>
        internal static string Reshape {
            get {
                return ResourceManager.GetString("Reshape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string RotateEnabled {
            get {
                return ResourceManager.GetString("RotateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling.
        /// </summary>
        internal static string ScaleEnabled {
            get {
                return ResourceManager.GetString("ScaleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only edit these layers:.
        /// </summary>
        internal static string SelectLayersForEdit {
            get {
                return ResourceManager.GetString("SelectLayersForEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select layers to edit.
        /// </summary>
        internal static string SelectLayersHeader {
            get {
                return ResourceManager.GetString("SelectLayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tools:.
        /// </summary>
        internal static string SelectTools {
            get {
                return ResourceManager.GetString("SelectTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display pop-ups on mouse click for layers selected for editing.
        /// </summary>
        internal static string SetLayerPopupOnClick {
            get {
                return ResourceManager.GetString("SetLayerPopupOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit values when features are added.
        /// </summary>
        internal static string ShowAttributesOnAdd {
            get {
                return ResourceManager.GetString("ShowAttributesOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        internal static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
    }
}
