/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintTool.AddIns.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintTool.AddIns.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectLabel {
            get {
                return ResourceManager.GetString("ConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPI:.
        /// </summary>
        public static string DpiLabel {
            get {
                return ResourceManager.GetString("DpiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing....
        /// </summary>
        public static string DrawingLabel {
            get {
                return ResourceManager.GetString("DrawingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details:.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format:.
        /// </summary>
        public static string FormatsLabel {
            get {
                return ResourceManager.GetString("FormatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get print layout templates completed..
        /// </summary>
        public static string GetLayoutTemplatesCompleted {
            get {
                return ResourceManager.GetString("GetLayoutTemplatesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get print layout templates started..
        /// </summary>
        public static string GetLayoutTemplatesStarted {
            get {
                return ResourceManager.GetString("GetLayoutTemplatesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get print layout XAML completed..
        /// </summary>
        public static string GetPrintLayoutXamlCompleted {
            get {
                return ResourceManager.GetString("GetPrintLayoutXamlCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get print layout XAML started..
        /// </summary>
        public static string GetPrintLayoutXamlStarted {
            get {
                return ResourceManager.GetString("GetPrintLayoutXamlStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        public static string LayoutLabel {
            get {
                return ResourceManager.GetString("LayoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template:.
        /// </summary>
        public static string LayoutTemplatesLabel {
            get {
                return ResourceManager.GetString("LayoutTemplatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading layout templates failed..
        /// </summary>
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ... .
        /// </summary>
        public static string LoadLabel {
            get {
                return ResourceManager.GetString("LoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster for layer {0} ({1}) will not be applied on output map..
        /// </summary>
        public static string NotSupportedClusterer {
            get {
                return ResourceManager.GetString("NotSupportedClusterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol of type {0} is not supported for printing and will be downgraded to default symbol for layer {1} ({2})..
        /// </summary>
        public static string NotSupportedGraphicSymbol {
            get {
                return ResourceManager.GetString("NotSupportedGraphicSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer of type {0} is not supported for printing and will be downgraded to default renderer for layer {1} ({2})..
        /// </summary>
        public static string NotSupportedLayerRenderer {
            get {
                return ResourceManager.GetString("NotSupportedLayerRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} of type {1} is not supported for printing and will be excluded in the output map..
        /// </summary>
        public static string NotSupportedLayerType {
            get {
                return ResourceManager.GetString("NotSupportedLayerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} is configured to use a proxy server.  Layers that use a proxy cannot be printed with ArcGIS Server and will be excluded from the output map..
        /// </summary>
        public static string NotSupportedLayerWithProxy {
            get {
                return ResourceManager.GetString("NotSupportedLayerWithProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print canceled..
        /// </summary>
        public static string PrintCanceled {
            get {
                return ResourceManager.GetString("PrintCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print request completed..
        /// </summary>
        public static string PrintCompleted {
            get {
                return ResourceManager.GetString("PrintCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Print.
        /// </summary>
        public static string PrintConfigTitle {
            get {
                return ResourceManager.GetString("PrintConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print failed..
        /// </summary>
        public static string PrintFailed {
            get {
                return ResourceManager.GetString("PrintFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintLabel {
            get {
                return ResourceManager.GetString("PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Print Layout.
        /// </summary>
        public static string PrintLayoutPickerTitle {
            get {
                return ResourceManager.GetString("PrintLayoutPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview:.
        /// </summary>
        public static string PrintPreviewLabel {
            get {
                return ResourceManager.GetString("PrintPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print request submitted..
        /// </summary>
        public static string PrintStarted {
            get {
                return ResourceManager.GetString("PrintStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string PrintToolCategory {
            get {
                return ResourceManager.GetString("PrintToolCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a printable output file..
        /// </summary>
        public static string PrintToolDescription {
            get {
                return ResourceManager.GetString("PrintToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string PrintToolTitle {
            get {
                return ResourceManager.GetString("PrintToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ArcGIS Server Print Service.
        /// </summary>
        public static string PrintWithArcGISServerLabel {
            get {
                return ResourceManager.GetString("PrintWithArcGISServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field..
        /// </summary>
        public static string RequiredFieldException {
            get {
                return ResourceManager.GetString("RequiredFieldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number greater than 0..
        /// </summary>
        public static string SizeFieldException {
            get {
                return ResourceManager.GetString("SizeFieldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Service URL:.
        /// </summary>
        public static string TaskUrlLabel {
            get {
                return ResourceManager.GetString("TaskUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy.
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        public static string UseScaleLabel {
            get {
                return ResourceManager.GetString("UseScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string VisibleLabel {
            get {
                return ResourceManager.GetString("VisibleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
    }
}
