/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see https://opensource.org/licenses/ms-pl for details.
All other rights reserved.
*/

using System;
using System.Globalization;
using System.Reflection;
using System.Windows.Data;

namespace ESRI.ArcGIS.Mapping.Controls
{
    /// <summary>
    /// Converts the data object bound to a datagrid row to the value of the field specified by the converter parameter
    /// </summary>
    public class RowToFieldValueConverter : IValueConverter
    {
        #region IValueConverter Members

        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (string.IsNullOrEmpty(parameter as string) || value == null)
                return null;

            // Get the property corresponding to the field name
            string fieldName = (string)parameter;

            // In the temp type generated by the DataGrid, non-ASCII characters are replaced with underscores
            fieldName = replaceNonAsciiCharacters(fieldName, "_");
            PropertyInfo property = value.GetType().GetProperty(fieldName);

            // Get the value
            if (property != null)
                return property.GetValue(value, null);
            else
                return null;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }

        #endregion

        private string replaceNonAsciiCharacters(string value, string replaceWith)
        {
            string escaped = "";
            foreach (char c in value)
            {
                if (c > 127)
                    escaped += replaceWith;
                else
                    escaped += c;
            }

            return escaped;
        }

    }
}
