/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see https://opensource.org/licenses/ms-pl for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Mapping.Controls.ArcGISOnline.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Mapping.Controls.ArcGISOnline.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Feature Layers.
        /// </summary>
        internal static string AddFeatureLayer {
            get {
                return ResourceManager.GetString("AddFeatureLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        internal static string AddFeatureLayerWindowCheckAll {
            get {
                return ResourceManager.GetString("AddFeatureLayerWindowCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        internal static string AddFeatureLayerWindowUnCheckAll {
            get {
                return ResourceManager.GetString("AddFeatureLayerWindowUnCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS.
        /// </summary>
        internal static string ArcGIS {
            get {
                return ResourceManager.GetString("ArcGIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Maps.
        /// </summary>
        internal static string BackStageControlFeatureMaps {
            get {
                return ResourceManager.GetString("BackStageControlFeatureMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string BackStageControlGroups {
            get {
                return ResourceManager.GetString("BackStageControlGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Groups.
        /// </summary>
        internal static string BackStageControlMyGroups {
            get {
                return ResourceManager.GetString("BackStageControlMyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Maps.
        /// </summary>
        internal static string BackStageControlMyMaps {
            get {
                return ResourceManager.GetString("BackStageControlMyMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organization&apos;s Groups.
        /// </summary>
        internal static string BackStageControlMyOrgGroups {
            get {
                return ResourceManager.GetString("BackStageControlMyOrgGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organization&apos;s Public Groups.
        /// </summary>
        internal static string BackStageControlMyOrgPublicGroups {
            get {
                return ResourceManager.GetString("BackStageControlMyOrgPublicGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string BackStageControlRecent {
            get {
                return ResourceManager.GetString("BackStageControlRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BackStageControlSearch {
            get {
                return ResourceManager.GetString("BackStageControlSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the description in a separate browser window.
        /// </summary>
        internal static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Details.
        /// </summary>
        internal static string CloseDetails {
            get {
                return ResourceManager.GetString("CloseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everyone.
        /// </summary>
        internal static string ContentEveryone {
            get {
                return ResourceManager.GetString("ContentEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string ContentGroups {
            get {
                return ResourceManager.GetString("ContentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by {0} on {1}.
        /// </summary>
        internal static string CreatedByOwnerOnDate {
            get {
                return ResourceManager.GetString("CreatedByOwnerOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias:.
        /// </summary>
        internal static string DefineQueryWindowAlias {
            get {
                return ResourceManager.GetString("DefineQueryWindowAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string DefineQueryWindowAnd {
            get {
                return ResourceManager.GetString("DefineQueryWindowAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string DefineQueryWindowApply {
            get {
                return ResourceManager.GetString("DefineQueryWindowApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to pick a date that is formatted for use in the expression..
        /// </summary>
        internal static string DefineQueryWindowClickPickDate {
            get {
                return ResourceManager.GetString("DefineQueryWindowClickPickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DefineQueryWindowData {
            get {
                return ResourceManager.GetString("DefineQueryWindowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression:.
        /// </summary>
        internal static string DefineQueryWindowExpression {
            get {
                return ResourceManager.GetString("DefineQueryWindowExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve sample features for layer..
        /// </summary>
        internal static string DefineQueryWindowFailedToRetrieveSampleFeaturesForLayer {
            get {
                return ResourceManager.GetString("DefineQueryWindowFailedToRetrieveSampleFeaturesForLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields:.
        /// </summary>
        internal static string DefineQueryWindowFields {
            get {
                return ResourceManager.GetString("DefineQueryWindowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        internal static string DefineQueryWindowLike {
            get {
                return ResourceManager.GetString("DefineQueryWindowLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string DefineQueryWindowName {
            get {
                return ResourceManager.GetString("DefineQueryWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not.
        /// </summary>
        internal static string DefineQueryWindowNot {
            get {
                return ResourceManager.GetString("DefineQueryWindowNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string DefineQueryWindowOr {
            get {
                return ResourceManager.GetString("DefineQueryWindowOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string DefineQueryWindowQuery {
            get {
                return ResourceManager.GetString("DefineQueryWindowQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following table is a sample of features in the layer..
        /// </summary>
        internal static string DefineQueryWindowTableIsSampleOfFeatureLayer {
            get {
                return ResourceManager.GetString("DefineQueryWindowTableIsSampleOfFeatureLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string DefineQueryWindowType {
            get {
                return ResourceManager.GetString("DefineQueryWindowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description for this group can&apos;t be displayed in this window..
        /// </summary>
        internal static string DescriptionForGroupCanotBeDisplayed {
            get {
                return ResourceManager.GetString("DescriptionForGroupCanotBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description for this map can&apos;t be displayed in this window..
        /// </summary>
        internal static string DescriptionForMapCanotBeDisplayed {
            get {
                return ResourceManager.GetString("DescriptionForMapCanotBeDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter place name; address; or latitude, longitude pair.
        /// </summary>
        internal static string EnterPlaceNameAddressLatLongitutePair {
            get {
                return ResourceManager.GetString("EnterPlaceNameAddressLatLongitutePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string ExceptionDeleteFailed {
            get {
                return ResourceManager.GetString("ExceptionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. User is not signed in..
        /// </summary>
        internal static string ExceptionDeleteFailedUserSignIn {
            get {
                return ResourceManager.GetString("ExceptionDeleteFailedUserSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept applicant {0} for group {1}.
        /// </summary>
        internal static string ExceptionFaileAcceptApplicateForGroup {
            get {
                return ResourceManager.GetString("ExceptionFaileAcceptApplicateForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decline applicant {0} for group {1}.
        /// </summary>
        internal static string ExceptionFaileDeclineApplicateForGroup {
            get {
                return ResourceManager.GetString("ExceptionFaileDeclineApplicateForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to invite users {0} to group {1}.
        /// </summary>
        internal static string ExceptionFailedInviteUserToGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedInviteUserToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send leave request for user {0} from group {1}.
        /// </summary>
        internal static string ExceptionFailedLeaveRequestForGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedLeaveRequestForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send join request for user {0} to group {1}.
        /// </summary>
        internal static string ExceptionFailedSendJoinRequestToGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedSendJoinRequestToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to accept group invitation for group {0} by {1}.
        /// </summary>
        internal static string ExceptionFailedToAcceptGroupInvitationForGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToAcceptGroupInvitationForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create group..
        /// </summary>
        internal static string ExceptionFailedToCreateGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decline group invitation for group {0} by {1}.
        /// </summary>
        internal static string ExceptionFailedToDeclineGroupInvitationForGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToDeclineGroupInvitationForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete group {0}.
        /// </summary>
        internal static string ExceptionFailedToDeleteGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete notification {0} by {1}.
        /// </summary>
        internal static string ExceptionFailedToDeleteNoitification {
            get {
                return ResourceManager.GetString("ExceptionFailedToDeleteNoitification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get group applications for group {0}.
        /// </summary>
        internal static string ExceptionFailedToGetGroupApplicationsForGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToGetGroupApplicationsForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve organizational groups.
        /// </summary>
        internal static string ExceptionFailedToRetrieveOrgGroups {
            get {
                return ResourceManager.GetString("ExceptionFailedToRetrieveOrgGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve tags for user {0}.
        /// </summary>
        internal static string ExceptionFailedToRetrieveTagForUser {
            get {
                return ResourceManager.GetString("ExceptionFailedToRetrieveTagForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to share item {0}.
        /// </summary>
        internal static string ExceptionFailedToShareItem {
            get {
                return ResourceManager.GetString("ExceptionFailedToShareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update group {0}.
        /// </summary>
        internal static string ExceptionFailedToUpdateGroup {
            get {
                return ResourceManager.GetString("ExceptionFailedToUpdateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get comments failed..
        /// </summary>
        internal static string ExceptionGetCommentsFailed {
            get {
                return ResourceManager.GetString("ExceptionGetCommentsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFolder failed. User is not signed in..
        /// </summary>
        internal static string ExceptionGetFolderFailedUserSignedIn {
            get {
                return ResourceManager.GetString("ExceptionGetFolderFailedUserSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user signed in..
        /// </summary>
        internal static string ExceptionNoUserSignedIn {
            get {
                return ResourceManager.GetString("ExceptionNoUserSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in failed..
        /// </summary>
        internal static string ExceptionSignInFailed {
            get {
                return ResourceManager.GetString("ExceptionSignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string FeatureMapsControlCloseParenthesis {
            get {
                return ResourceManager.GetString("FeatureMapsControlCloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string FeatureMapsControlDetails {
            get {
                return ResourceManager.GetString("FeatureMapsControlDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (last modified: .
        /// </summary>
        internal static string FeatureMapsControlLastModified {
            get {
                return ResourceManager.GetString("FeatureMapsControlLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FeatureMapsControlOpen {
            get {
                return ResourceManager.GetString("FeatureMapsControlOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view the description in a separate browser window.
        /// </summary>
        internal static string GroupControlClickHereToViewInSeparateBrowser {
            get {
                return ResourceManager.GetString("GroupControlClickHereToViewInSeparateBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this Group.
        /// </summary>
        internal static string GroupControlCloseGroup {
            get {
                return ResourceManager.GetString("GroupControlCloseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string GroupControlDescription {
            get {
                return ResourceManager.GetString("GroupControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Maps.
        /// </summary>
        internal static string GroupControlFeaturedMaps {
            get {
                return ResourceManager.GetString("GroupControlFeaturedMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No featured maps found..
        /// </summary>
        internal static string GroupControlNoFeaturedMapsFound {
            get {
                return ResourceManager.GetString("GroupControlNoFeaturedMapsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No maps found..
        /// </summary>
        internal static string GroupControlNoMapsFound {
            get {
                return ResourceManager.GetString("GroupControlNoMapsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string GroupControlOwner {
            get {
                return ResourceManager.GetString("GroupControlOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Owner).
        /// </summary>
        internal static string GroupControlOwnerParenthesis {
            get {
                return ResourceManager.GetString("GroupControlOwnerParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private (Users cannot find the group and can join by invitation only).
        /// </summary>
        internal static string GroupControlPrivateUserCannotFindGroup {
            get {
                return ResourceManager.GetString("GroupControlPrivateUserCannotFindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public (Users can search for and find the group).
        /// </summary>
        internal static string GroupControlPublicUserCanSearchAndFindGroup {
            get {
                return ResourceManager.GetString("GroupControlPublicUserCanSearchAndFindGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to owner: {0}.
        /// </summary>
        internal static string GroupControlSearchOwner {
            get {
                return ResourceManager.GetString("GroupControlSearchOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string GroupControlTags {
            get {
                return ResourceManager.GetString("GroupControlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Rated.
        /// </summary>
        internal static string HighestRated {
            get {
                return ResourceManager.GetString("HighestRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter place name; address; or latitude,longitude pair.
        /// </summary>
        internal static string HintTextBoxToolTip {
            get {
                return ResourceManager.GetString("HintTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID or password..
        /// </summary>
        internal static string InvalidIDOrPassword {
            get {
                return ResourceManager.GetString("InvalidIDOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found: {0}.
        /// </summary>
        internal static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (last modified:.
        /// </summary>
        internal static string LastModifiedPrompt {
            get {
                return ResourceManager.GetString("LastModifiedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string LastModifiedPromptEnd {
            get {
                return ResourceManager.GetString("LastModifiedPromptEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Maps....
        /// </summary>
        internal static string LoadingMaps {
            get {
                return ResourceManager.GetString("LoadingMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        internal static string MapDetailsControlAverageRating {
            get {
                return ResourceManager.GetString("MapDetailsControlAverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MapDetailsControlType {
            get {
                return ResourceManager.GetString("MapDetailsControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} ratings).
        /// </summary>
        internal static string MapDetailsRating {
            get {
                return ResourceManager.GetString("MapDetailsRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map service reference is invalid. The service could not be added to the map..
        /// </summary>
        internal static string MapServiceReferenceInvalid {
            get {
                return ResourceManager.GetString("MapServiceReferenceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map service reference is invalid. No details can be displayed..
        /// </summary>
        internal static string MapServiceReferenceNoDetails {
            get {
                return ResourceManager.GetString("MapServiceReferenceNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Comments.
        /// </summary>
        internal static string MostComments {
            get {
                return ResourceManager.GetString("MostComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        internal static string MostPopular {
            get {
                return ResourceManager.GetString("MostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recently Added.
        /// </summary>
        internal static string MostRecentlyAdded {
            get {
                return ResourceManager.GetString("MostRecentlyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Relevant.
        /// </summary>
        internal static string MostRelevant {
            get {
                return ResourceManager.GetString("MostRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} groups.
        /// </summary>
        internal static string MyGroupControlGroups {
            get {
                return ResourceManager.GetString("MyGroupControlGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string MyGroupControlOn {
            get {
                return ResourceManager.GetString("MyGroupControlOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this group.
        /// </summary>
        internal static string MyGroupControlOpenGroup {
            get {
                return ResourceManager.GetString("MyGroupControlOpenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 groups.
        /// </summary>
        internal static string MyGroupControlZeroGroups {
            get {
                return ResourceManager.GetString("MyGroupControlZeroGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maps.
        /// </summary>
        internal static string MyMapControlMaps {
            get {
                return ResourceManager.GetString("MyMapControlMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 maps.
        /// </summary>
        internal static string MyMapControlZeroMaps {
            get {
                return ResourceManager.GetString("MyMapControlZeroMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New here?.
        /// </summary>
        internal static string NewHere {
            get {
                return ResourceManager.GetString("NewHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No featured maps currently available.
        /// </summary>
        internal static string NoFeaturedMaps {
            get {
                return ResourceManager.GetString("NoFeaturedMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on .
        /// </summary>
        internal static string OnWithSpace {
            get {
                return ResourceManager.GetString("OnWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordPrompt {
            get {
                return ResourceManager.GetString("PasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Maps.
        /// </summary>
        internal static string RecentMaps {
            get {
                return ResourceManager.GetString("RecentMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ArcGIS.com.
        /// </summary>
        internal static string SearchArcGISCom {
            get {
                return ResourceManager.GetString("SearchArcGISCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SearchControlAdd {
            get {
                return ResourceManager.GetString("SearchControlAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map service found..
        /// </summary>
        internal static string SearchControlMapServiceFound {
            get {
                return ResourceManager.GetString("SearchControlMapServiceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results found..
        /// </summary>
        internal static string SearchControlResultsFound {
            get {
                return ResourceManager.GetString("SearchControlResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service could not be accessed..
        /// </summary>
        internal static string SearchControlServiceCouldNotBeAccessed {
            get {
                return ResourceManager.GetString("SearchControlServiceCouldNotBeAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 results found..
        /// </summary>
        internal static string SearchControlZeroResultsFound {
            get {
                return ResourceManager.GetString("SearchControlZeroResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string SearchDetailsBy {
            get {
                return ResourceManager.GetString("SearchDetailsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: .
        /// </summary>
        internal static string SearchDetailsRating {
            get {
                return ResourceManager.GetString("SearchDetailsRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results for {1}.
        /// </summary>
        internal static string SearchMapResultsFor {
            get {
                return ResourceManager.GetString("SearchMapResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        internal static string SearchR {
            get {
                return ResourceManager.GetString("SearchR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter place name; address; or latitude, longitude pair.
        /// </summary>
        internal static string SearchTextBoxToolTip {
            get {
                return ResourceManager.GetString("SearchTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the web&quot;.
        /// </summary>
        internal static string SearchTheWeb {
            get {
                return ResourceManager.GetString("SearchTheWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string SearchWebDetailsAdd {
            get {
                return ResourceManager.GetString("SearchWebDetailsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: .
        /// </summary>
        internal static string SearchWebDetailsCopyright {
            get {
                return ResourceManager.GetString("SearchWebDetailsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        internal static string SearchWebDetailsDescription {
            get {
                return ResourceManager.GetString("SearchWebDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore this GIS server.
        /// </summary>
        internal static string SearchWebDetailsExploreGISServer {
            get {
                return ResourceManager.GetString("SearchWebDetailsExploreGISServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string SearchWebDetailsName {
            get {
                return ResourceManager.GetString("SearchWebDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in failed..
        /// </summary>
        internal static string SignInFailed {
            get {
                return ResourceManager.GetString("SignInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string SignInForgotYourPassword {
            get {
                return ResourceManager.GetString("SignInForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to {0}.
        /// </summary>
        internal static string SignInLabel {
            get {
                return ResourceManager.GetString("SignInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignInSignUp {
            get {
                return ResourceManager.GetString("SignInSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Results.
        /// </summary>
        internal static string SortResults {
            get {
                return ResourceManager.GetString("SortResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort the search results..
        /// </summary>
        internal static string SortSearchResults {
            get {
                return ResourceManager.GetString("SortSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web.
        /// </summary>
        internal static string TheWeb {
            get {
                return ResourceManager.GetString("TheWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title A-Z.
        /// </summary>
        internal static string TitleAZ {
            get {
                return ResourceManager.GetString("TitleAZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Z-A.
        /// </summary>
        internal static string TitleZA {
            get {
                return ResourceManager.GetString("TitleZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UsernamePrompt {
            get {
                return ResourceManager.GetString("UsernamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User search failed..
        /// </summary>
        internal static string UserSearchFailed {
            get {
                return ResourceManager.GetString("UserSearchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Map by {0}.
        /// </summary>
        internal static string WebMapBy {
            get {
                return ResourceManager.GetString("WebMapBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Map by {0} (last modified: {1}).
        /// </summary>
        internal static string WebMapOwnerDateFormat {
            get {
                return ResourceManager.GetString("WebMapOwnerDateFormat", resourceCulture);
            }
        }
    }
}
