/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeasureTool.Addins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeasureTool.Addins.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: {0}.
        /// </summary>
        public static string AreaLabelFormat {
            get {
                return ResourceManager.GetString("AreaLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter cannot convert back.
        /// </summary>
        public static string ConverterCannotConvertBack {
            get {
                return ResourceManager.GetString("ConverterCannotConvertBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to place another point.
        /// </summary>
        public static string DrawClickContinue {
            get {
                return ResourceManager.GetString("DrawClickContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to place another point or double-click to finish.
        /// </summary>
        public static string DrawClickContinueDoubleClickFinish {
            get {
                return ResourceManager.GetString("DrawClickContinueDoubleClickFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag to start drawing.
        /// </summary>
        public static string DrawClickDrag {
            get {
                return ResourceManager.GetString("DrawClickDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to place the first point.
        /// </summary>
        public static string DrawClickStart {
            get {
                return ResourceManager.GetString("DrawClickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrawPopupBehavior can only be attached to Draw objects that are associated with a Map.
        /// </summary>
        public static string DrawPopupBehaviorNoMap {
            get {
                return ResourceManager.GetString("DrawPopupBehaviorNoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release the mouse to finish drawing.
        /// </summary>
        public static string DrawReleaseFinish {
            get {
                return ResourceManager.GetString("DrawReleaseFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to draw a point.
        /// </summary>
        public static string DrawShapePoint {
            get {
                return ResourceManager.GetString("DrawShapePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ErrorDetails {
            get {
                return ResourceManager.GetString("ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL to a geometry service must be specified for measuring geometries that require reprojection.
        /// </summary>
        public static string GeometryServiceNotSpecified {
            get {
                return ResourceManager.GetString("GeometryServiceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer:.
        /// </summary>
        public static string LayerPrompt {
            get {
                return ResourceManager.GetString("LayerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length: {0}.
        /// </summary>
        public static string LengthLabelFormat {
            get {
                return ResourceManager.GetString("LengthLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure operation failed.
        /// </summary>
        public static string MeasureFailed {
            get {
                return ResourceManager.GetString("MeasureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        public static string MeasureLabelArea {
            get {
                return ResourceManager.GetString("MeasureLabelArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click another feature for new measurements.
        /// </summary>
        public static string MeasureLabelClickAnotherFeature {
            get {
                return ResourceManager.GetString("MeasureLabelClickAnotherFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a feature from the {0} layer.
        /// </summary>
        public static string MeasureLabelClickFeature {
            get {
                return ResourceManager.GetString("MeasureLabelClickFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features to measure.
        /// </summary>
        public static string MeasureLabelFeaturesMap {
            get {
                return ResourceManager.GetString("MeasureLabelFeaturesMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string MeasureLabelLatitude {
            get {
                return ResourceManager.GetString("MeasureLabelLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string MeasureLabelLength {
            get {
                return ResourceManager.GetString("MeasureLabelLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string MeasureLabelLongitude {
            get {
                return ResourceManager.GetString("MeasureLabelLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string MeasureLabelMeasurements {
            get {
                return ResourceManager.GetString("MeasureLabelMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter:.
        /// </summary>
        public static string MeasureLabelPerimeter {
            get {
                return ResourceManager.GetString("MeasureLabelPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw shapes to measure.
        /// </summary>
        public static string MeasureLabelShapesDraw {
            get {
                return ResourceManager.GetString("MeasureLabelShapesDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0,0.0000} {1}.
        /// </summary>
        public static string MeasurementFormat {
            get {
                return ResourceManager.GetString("MeasurementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        public static string MeasureTitle {
            get {
                return ResourceManager.GetString("MeasureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string MeasureToolCategory {
            get {
                return ResourceManager.GetString("MeasureToolCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get measurements from existing features or by drawing on the map.
        /// </summary>
        public static string MeasureToolDescription {
            get {
                return ResourceManager.GetString("MeasureToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported geometry type for measure operation.
        /// </summary>
        public static string MeasureUnsupportedGeometryType {
            get {
                return ResourceManager.GetString("MeasureUnsupportedGeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features found.  Please try again or choose a different layer..
        /// </summary>
        public static string NoFeaturesFound {
            get {
                return ResourceManager.GetString("NoFeaturesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation only supported on geometries with a Web Mercator or WGS84 spatial reference.
        /// </summary>
        public static string NonClientSpatialRef {
            get {
                return ResourceManager.GetString("NonClientSpatialRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to project geometry to WGS 84. No results returned from {0}..
        /// </summary>
        public static string NoProjectionResults {
            get {
                return ResourceManager.GetString("NoProjectionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter: {0}.
        /// </summary>
        public static string PerimeterLabelFormat {
            get {
                return ResourceManager.GetString("PerimeterLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to project geometry to WGS 84 using {0}.  Error:
        ///{1}.
        /// </summary>
        public static string ProjectFailure {
            get {
                return ResourceManager.GetString("ProjectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target geometry, output spatial reference, and URL to a geometry service must be specified.
        /// </summary>
        public static string ProjectInputsNotValid {
            get {
                return ResourceManager.GetString("ProjectInputsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Failed: {0}.
        /// </summary>
        public static string QueryFailed {
            get {
                return ResourceManager.GetString("QueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius: {0}.
        /// </summary>
        public static string RadiusLabelFormat {
            get {
                return ResourceManager.GetString("RadiusLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment: {0}.
        /// </summary>
        public static string SegmentLengthLabelFormat {
            get {
                return ResourceManager.GetString("SegmentLengthLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to simplify geometry using {0}.  Error:
        ///{1}.
        /// </summary>
        public static string SimplifyFailed {
            get {
                return ResourceManager.GetString("SimplifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target geometry and URL to a geometry service must be defined.
        /// </summary>
        public static string SimplifyInputsNotValid {
            get {
                return ResourceManager.GetString("SimplifyInputsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation complete.  Draw to measure again..
        /// </summary>
        public static string StatusCalculateCompleteDrawAgain {
            get {
                return ResourceManager.GetString("StatusCalculateCompleteDrawAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating....
        /// </summary>
        public static string StatusCalculating {
            get {
                return ResourceManager.GetString("StatusCalculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a shape to draw.
        /// </summary>
        public static string StatusClickShapeButton {
            get {
                return ResourceManager.GetString("StatusClickShapeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing....
        /// </summary>
        public static string StatusDrawing {
            get {
                return ResourceManager.GetString("StatusDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a shape on the map.
        /// </summary>
        public static string StatusDrawShape {
            get {
                return ResourceManager.GetString("StatusDrawShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-layer:.
        /// </summary>
        public static string SubLayerPrompt {
            get {
                return ResourceManager.GetString("SubLayerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string TooltipCircle {
            get {
                return ResourceManager.GetString("TooltipCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        public static string TooltipEllipse {
            get {
                return ResourceManager.GetString("TooltipEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freehand Line.
        /// </summary>
        public static string TooltipFreehandLine {
            get {
                return ResourceManager.GetString("TooltipFreehandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freehand Polygon.
        /// </summary>
        public static string TooltipFreehandPolygon {
            get {
                return ResourceManager.GetString("TooltipFreehandPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string TooltipPoint {
            get {
                return ResourceManager.GetString("TooltipPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string TooltipPolygon {
            get {
                return ResourceManager.GetString("TooltipPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string TooltipPolyline {
            get {
                return ResourceManager.GetString("TooltipPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string TooltipRectangle {
            get {
                return ResourceManager.GetString("TooltipRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string TotalLengthLabelFormat {
            get {
                return ResourceManager.GetString("TotalLengthLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acres.
        /// </summary>
        public static string UnitsAcres {
            get {
                return ResourceManager.GetString("UnitsAcres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string UnitsCentimeters {
            get {
                return ResourceManager.GetString("UnitsCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string UnitsFeet {
            get {
                return ResourceManager.GetString("UnitsFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        public static string UnitsHectares {
            get {
                return ResourceManager.GetString("UnitsHectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string UnitsInches {
            get {
                return ResourceManager.GetString("UnitsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string UnitsKilometers {
            get {
                return ResourceManager.GetString("UnitsKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string UnitsMeters {
            get {
                return ResourceManager.GetString("UnitsMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string UnitsMiles {
            get {
                return ResourceManager.GetString("UnitsMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles.
        /// </summary>
        public static string UnitsNauticalMiles {
            get {
                return ResourceManager.GetString("UnitsNauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Feet.
        /// </summary>
        public static string UnitsSquareFeet {
            get {
                return ResourceManager.GetString("UnitsSquareFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Kilometers.
        /// </summary>
        public static string UnitsSquareKilometers {
            get {
                return ResourceManager.GetString("UnitsSquareKilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Meters.
        /// </summary>
        public static string UnitsSquareMeters {
            get {
                return ResourceManager.GetString("UnitsSquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Miles.
        /// </summary>
        public static string UnitsSquareMiles {
            get {
                return ResourceManager.GetString("UnitsSquareMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        public static string UnitsYards {
            get {
                return ResourceManager.GetString("UnitsYards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported layer type for selecting features.
        /// </summary>
        public static string UnsupportedLayerType {
            get {
                return ResourceManager.GetString("UnsupportedLayerType", resourceCulture);
            }
        }
    }
}
