/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see https://opensource.org/licenses/ms-pl for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Mapping.Controls.MapContents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Mapping.Controls.MapContents.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow layer selection.
        /// </summary>
        internal static string AllowLayerSelection {
            get {
                return ResourceManager.GetString("AllowLayerSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Map Contents.
        /// </summary>
        internal static string ConfigureMapContents {
            get {
                return ResourceManager.GetString("ConfigureMapContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Symbol.
        /// </summary>
        internal static string DefaultLegentItemViewModelLabel {
            get {
                return ResourceManager.GetString("DefaultLegentItemViewModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers to be excluded from map contents:.
        /// </summary>
        internal static string ExcludedLayerList {
            get {
                return ResourceManager.GetString("ExcludedLayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand layers on add.
        /// </summary>
        internal static string ExpandLayersOnAdd {
            get {
                return ResourceManager.GetString("ExpandLayersOnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide basemap layer(s).
        /// </summary>
        internal static string HideBaseMaps {
            get {
                return ResourceManager.GetString("HideBaseMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Display Mode:.
        /// </summary>
        internal static string LayerDisplayMode {
            get {
                return ResourceManager.GetString("LayerDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer List.
        /// </summary>
        internal static string LayerList {
            get {
                return ResourceManager.GetString("LayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist layer expanded state.
        /// </summary>
        internal static string PersistIsExpandedState {
            get {
                return ResourceManager.GetString("PersistIsExpandedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only layers visible at current scale.
        /// </summary>
        internal static string ShowLayersVisibleAtScale {
            get {
                return ResourceManager.GetString("ShowLayersVisibleAtScale", resourceCulture);
            }
        }
    }
}
