/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Mapping.Builder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Mapping.Builder.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the About dialog of Application Builder.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Application Builder.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent Text.
        /// </summary>
        internal static string AccentText {
            get {
                return ResourceManager.GetString("AccentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access secured services.
        /// </summary>
        internal static string AccessSecuredServices {
            get {
                return ResourceManager.GetString("AccessSecuredServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Behavior.
        /// </summary>
        internal static string AddBehavior {
            get {
                return ResourceManager.GetString("AddBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a behavior to the Viewer.
        /// </summary>
        internal static string AddBehaviorDescription {
            get {
                return ResourceManager.GetString("AddBehaviorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Geoprocessing.
        /// </summary>
        internal static string AddGeoprocessing {
            get {
                return ResourceManager.GetString("AddGeoprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a geoprocessing tool to the Viewer.  A geoprocessing tool allows users of the Viewer to use an ArcGIS Server Geoprocessing Service..
        /// </summary>
        internal static string AddGeoprocessingDescription {
            get {
                return ResourceManager.GetString("AddGeoprocessingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a geo-enabled RSS feed to the map.
        /// </summary>
        internal static string AddGeoRSSDescription {
            get {
                return ResourceManager.GetString("AddGeoRSSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GP.
        /// </summary>
        internal static string AddGP {
            get {
                return ResourceManager.GetString("AddGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string AddGroupButton {
            get {
                return ResourceManager.GetString("AddGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group....
        /// </summary>
        internal static string AddGroupDotDot {
            get {
                return ResourceManager.GetString("AddGroupDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In packages contain add-ins: tools, behaviors and controls used in layouts.
        /// </summary>
        internal static string AddInPackagesContain {
            get {
                return ResourceManager.GetString("AddInPackagesContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Layer Failed.
        /// </summary>
        internal static string AddLayerFailed {
            get {
                return ResourceManager.GetString("AddLayerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer could not be added. Reason for failure: {0}..
        /// </summary>
        internal static string AddLayerFailedExplanation {
            get {
                return ResourceManager.GetString("AddLayerFailedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No details could be extracted].
        /// </summary>
        internal static string AddLayerFailedNoDetails {
            get {
                return ResourceManager.GetString("AddLayerFailedNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Link.
        /// </summary>
        internal static string AddLink {
            get {
                return ResourceManager.GetString("AddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new group or control.
        /// </summary>
        internal static string AddNewGroupOrControl {
            get {
                return ResourceManager.GetString("AddNewGroupOrControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-Ins.
        /// </summary>
        internal static string AddOns {
            get {
                return ResourceManager.GetString("AddOns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Secured Services.
        /// </summary>
        internal static string AddSecuredServices {
            get {
                return ResourceManager.GetString("AddSecuredServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Separator.
        /// </summary>
        internal static string AddSeparator {
            get {
                return ResourceManager.GetString("AddSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tool.
        /// </summary>
        internal static string AddTool {
            get {
                return ResourceManager.GetString("AddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tool to the Viewer.
        /// </summary>
        internal static string AddToolDescription {
            get {
                return ResourceManager.GetString("AddToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Builder - Settings.
        /// </summary>
        internal static string ApplicationBuilderDashSettings {
            get {
                return ResourceManager.GetString("ApplicationBuilderDashSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Builder Settings.
        /// </summary>
        internal static string ApplicationBuilderSettings {
            get {
                return ResourceManager.GetString("ApplicationBuilderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and modify the settings of Application Builder including management of add-ins and basemaps..
        /// </summary>
        internal static string ApplicationBuilderSettingsDescription {
            get {
                return ResourceManager.GetString("ApplicationBuilderSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Properties.
        /// </summary>
        internal static string ApplicationProperties {
            get {
                return ResourceManager.GetString("ApplicationProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Builder - {0}.
        /// </summary>
        internal static string ArcGISApplicationBuilder {
            get {
                return ResourceManager.GetString("ArcGISApplicationBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Online Secure:.
        /// </summary>
        internal static string ArcGISOnlineSecure {
            get {
                return ResourceManager.GetString("ArcGISOnlineSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Online Sharing:.
        /// </summary>
        internal static string ArcGISOnlineSharing {
            get {
                return ResourceManager.GetString("ArcGISOnlineSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Viewer for Silverlight.
        /// </summary>
        internal static string ArcGISViewerForMicrosoftSilverlight {
            get {
                return ResourceManager.GetString("ArcGISViewerForMicrosoftSilverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this button?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteButton {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this group?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteGroup {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this web site?.
        /// </summary>
        internal static string AreYouSureYouWantToDeleteWebSite {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this page? Any unsaved changes might be lost..
        /// </summary>
        internal static string AreYouSureYouWantToLeavePageUnsavedChangesLost {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToLeavePageUnsavedChangesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}The assembly &apos;{0}&apos; is already included in the application runtime.{1}Consider optimizing the size and download speed of your extension by marking the Assembly Reference with CopyLocal=false to exclude the assembly in the .xap packaging.
        /// </summary>
        internal static string AssemblyAlreadyIncludeInTheApplication {
            get {
                return ResourceManager.GetString("AssemblyAlreadyIncludeInTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Table.
        /// </summary>
        internal static string AttributeTable {
            get {
                return ResourceManager.GetString("AttributeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Add-In Packages:.
        /// </summary>
        internal static string AvailableAddInPackages {
            get {
                return ResourceManager.GetString("AvailableAddInPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Tools.
        /// </summary>
        internal static string AvailableTools {
            get {
                return ResourceManager.GetString("AvailableTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Text.
        /// </summary>
        internal static string BackgroundText {
            get {
                return ResourceManager.GetString("BackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Web Map:.
        /// </summary>
        internal static string BasedOnWebMap {
            get {
                return ResourceManager.GetString("BasedOnWebMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a different base layer for the map.
        /// </summary>
        internal static string BasemapGalleryDescription {
            get {
                return ResourceManager.GetString("BasemapGalleryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basemaps.
        /// </summary>
        internal static string BaseMaps {
            get {
                return ResourceManager.GetString("BaseMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaviors.
        /// </summary>
        internal static string Behaviors {
            get {
                return ResourceManager.GetString("Behaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing AppID:.
        /// </summary>
        internal static string BingAppId {
            get {
                return ResourceManager.GetString("BingAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding.
        /// </summary>
        internal static string Branding {
            get {
                return ResourceManager.GetString("Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string BringForward {
            get {
                return ResourceManager.GetString("BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the layer&apos;s display order one position closer to the top of the map.
        /// </summary>
        internal static string BringsCurrentlySelectedLayerForward {
            get {
                return ResourceManager.GetString("BringsCurrentlySelectedLayerForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for file.
        /// </summary>
        internal static string BrowseForFile {
            get {
                return ResourceManager.GetString("BrowseForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for image.
        /// </summary>
        internal static string BrowseForImage {
            get {
                return ResourceManager.GetString("BrowseForImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for resource.
        /// </summary>
        internal static string BrowseForResource {
            get {
                return ResourceManager.GetString("BrowseForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder Tutorial.
        /// </summary>
        internal static string BuilderTutorial {
            get {
                return ResourceManager.GetString("BuilderTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add drop down commands to a group..
        /// </summary>
        internal static string CannotAddDropdownCommandsToAGroup {
            get {
                return ResourceManager.GetString("CannotAddDropdownCommandsToAGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Element.
        /// </summary>
        internal static string CannotAddElement {
            get {
                return ResourceManager.GetString("CannotAddElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Group.
        /// </summary>
        internal static string CannotAddGroupButton {
            get {
                return ResourceManager.GetString("CannotAddGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Tool.
        /// </summary>
        internal static string CannotAddTool {
            get {
                return ResourceManager.GetString("CannotAddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Layout.
        /// </summary>
        internal static string ChangeLayout {
            get {
                return ResourceManager.GetString("ChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new layout for the Viewer.
        /// </summary>
        internal static string ChangeLayoutDescription {
            get {
                return ResourceManager.GetString("ChangeLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Logo.
        /// </summary>
        internal static string ChangeLogo {
            get {
                return ResourceManager.GetString("ChangeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a logo for the Viewer.
        /// </summary>
        internal static string ChangeLogoDescription {
            get {
                return ResourceManager.GetString("ChangeLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully..
        /// </summary>
        internal static string ChangesSavedSuccessfully {
            get {
                return ResourceManager.GetString("ChangesSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Title and Links.
        /// </summary>
        internal static string ChangeTitleAndLinks {
            get {
                return ResourceManager.GetString("ChangeTitleAndLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the Viewer&apos;s title and hyperlinks.
        /// </summary>
        internal static string ChangeTitleAndLinksDescription {
            get {
                return ResourceManager.GetString("ChangeTitleAndLinksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an individual tool from the Available Tools tree..
        /// </summary>
        internal static string ChooseAvailableTool {
            get {
                return ResourceManager.GetString("ChooseAvailableTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose existing project.
        /// </summary>
        internal static string ChooseExistingProject {
            get {
                return ResourceManager.GetString("ChooseExistingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Layout.
        /// </summary>
        internal static string ChooseLayout {
            get {
                return ResourceManager.GetString("ChooseLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Builder - Choose a Map.
        /// </summary>
        internal static string ChooseMap {
            get {
                return ResourceManager.GetString("ChooseMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Basemaps.
        /// </summary>
        internal static string ConfigureBasemaps {
            get {
                return ResourceManager.GetString("ConfigureBasemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Controls.
        /// </summary>
        internal static string ConfigureControls {
            get {
                return ResourceManager.GetString("ConfigureControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls To Configure.
        /// </summary>
        internal static string ConfigureControlsBanner {
            get {
                return ResourceManager.GetString("ConfigureControlsBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the configuration of the Viewer&apos;s controls.
        /// </summary>
        internal static string ConfigureControlsDescription {
            get {
                return ResourceManager.GetString("ConfigureControlsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the currently selected layer.
        /// </summary>
        internal static string ConfigureCurrentlySelectedLayer {
            get {
                return ResourceManager.GetString("ConfigureCurrentlySelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure elements related to the map.
        /// </summary>
        internal static string ConfigureElementsRelatedToMap {
            get {
                return ResourceManager.GetString("ConfigureElementsRelatedToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Extensions.
        /// </summary>
        internal static string ConfigureExtensions {
            get {
                return ResourceManager.GetString("ConfigureExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Layers.
        /// </summary>
        internal static string ConfigureLayers {
            get {
                return ResourceManager.GetString("ConfigureLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the appearance and behavior of layers in the map.
        /// </summary>
        internal static string ConfigureLayersDescription {
            get {
                return ResourceManager.GetString("ConfigureLayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure options that apply to the current user.
        /// </summary>
        internal static string ConfigureOptionsThatApplyToCurrentUser {
            get {
                return ResourceManager.GetString("ConfigureOptionsThatApplyToCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Proxy.
        /// </summary>
        internal static string ConfigureProxy {
            get {
                return ResourceManager.GetString("ConfigureProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the proxy used to access secure services for this application.
        /// </summary>
        internal static string ConfigureProxyUsedToAccessSecureServicesForApplication {
            get {
                return ResourceManager.GetString("ConfigureProxyUsedToAccessSecureServicesForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Secure Services.
        /// </summary>
        internal static string ConfigureSecureServices {
            get {
                return ResourceManager.GetString("ConfigureSecureServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the selected group or control.
        /// </summary>
        internal static string ConfigureSelectedGroupOrControl {
            get {
                return ResourceManager.GetString("ConfigureSelectedGroupOrControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the set of basemaps available in the Application Builder.
        /// </summary>
        internal static string ConfigureSetOfBaseMapsUsedByBuilder {
            get {
                return ResourceManager.GetString("ConfigureSetOfBaseMapsUsedByBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Theme.
        /// </summary>
        internal static string ConfigureTheme {
            get {
                return ResourceManager.GetString("ConfigureTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the Viewer&apos;s theme colors.
        /// </summary>
        internal static string ConfigureThemeDescription {
            get {
                return ResourceManager.GetString("ConfigureThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the tools of your application.
        /// </summary>
        internal static string ConfigureToolsOfYourApplication {
            get {
                return ResourceManager.GetString("ConfigureToolsOfYourApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Page Change.
        /// </summary>
        internal static string ConfirmPageChange {
            get {
                return ResourceManager.GetString("ConfirmPageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Site.
        /// </summary>
        internal static string CopySite {
            get {
                return ResourceManager.GetString("CopySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string CreateApplicationUsingDefaultMap {
            get {
                return ResourceManager.GetString("CreateApplicationUsingDefaultMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Maps.
        /// </summary>
        internal static string CreateApplicationUsingWebMapFromArcGISCom {
            get {
                return ResourceManager.GetString("CreateApplicationUsingWebMapFromArcGISCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Application.
        /// </summary>
        internal static string CreateNewApplication {
            get {
                return ResourceManager.GetString("CreateNewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Application Settings.
        /// </summary>
        internal static string CurrentApplicationSettings {
            get {
                return ResourceManager.GetString("CurrentApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Toolbars.
        /// </summary>
        internal static string CurrentToolbars {
            get {
                return ResourceManager.GetString("CurrentToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Viewer Applications.
        /// </summary>
        internal static string CurrentViewerApplications {
            get {
                return ResourceManager.GetString("CurrentViewerApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string DefaultGroupButtonDescription {
            get {
                return ResourceManager.GetString("DefaultGroupButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string DefaultGroupButtonLabel {
            get {
                return ResourceManager.GetString("DefaultGroupButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        internal static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Site.
        /// </summary>
        internal static string DeleteSite {
            get {
                return ResourceManager.GetString("DeleteSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting an extension will make it unavailable for further use in new applications and edits on existing applications. {0}Are you sure you want to delete?.
        /// </summary>
        internal static string DeletingExtensionWillMakeItUnavailableForFurtherUse {
            get {
                return ResourceManager.GetString("DeletingExtensionWillMakeItUnavailableForFurtherUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting site....
        /// </summary>
        internal static string DeletingSite {
            get {
                return ResourceManager.GetString("DeletingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying Application....
        /// </summary>
        internal static string DeployingApplication {
            get {
                return ResourceManager.GetString("DeployingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DescriptionPrompt {
            get {
                return ResourceManager.GetString("DescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Getting Started.
        /// </summary>
        internal static string DisableGettingStarted {
            get {
                return ResourceManager.GetString("DisableGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Text.
        /// </summary>
        internal static string DisplayText {
            get {
                return ResourceManager.GetString("DisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected group or control.
        /// </summary>
        internal static string EditSelectedGroupOrControl {
            get {
                return ResourceManager.GetString("EditSelectedGroupOrControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Site.
        /// </summary>
        internal static string EditSite {
            get {
                return ResourceManager.GetString("EditSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tool.
        /// </summary>
        internal static string EditTool {
            get {
                return ResourceManager.GetString("EditTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the application.
        /// </summary>
        internal static string EnterNameForApplication {
            get {
                return ResourceManager.GetString("EnterNameForApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details not known.
        /// </summary>
        internal static string ErrorDetailsNotKnown {
            get {
                return ResourceManager.GetString("ErrorDetailsNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving map document for site.
        /// </summary>
        internal static string ErrorRetrievingMapDocumentForSite {
            get {
                return ResourceManager.GetString("ErrorRetrievingMapDocumentForSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve details for add-in package..
        /// </summary>
        internal static string ErrorUnableToRetrieveDetailsForExtension {
            get {
                return ResourceManager.GetString("ErrorUnableToRetrieveDetailsForExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Error {0}.
        /// </summary>
        internal static string ExceptionUnhandledError {
            get {
                return ResourceManager.GetString("ExceptionUnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in already exists.
        /// </summary>
        internal static string ExtensionAlreadyExists {
            get {
                return ResourceManager.GetString("ExtensionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add-in package &apos;{0}&apos; contains the following add-ins:.
        /// </summary>
        internal static string ExtensionContainsTheFollowingAddOns {
            get {
                return ResourceManager.GetString("ExtensionContainsTheFollowingAddOns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-In Details: {0}.
        /// </summary>
        internal static string ExtensionDetails {
            get {
                return ResourceManager.GetString("ExtensionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Notifications.
        /// </summary>
        internal static string ExtensionNotifications {
            get {
                return ResourceManager.GetString("ExtensionNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add-in package that you are attempting to deploy contains errors. These must be resolved before continuing..
        /// </summary>
        internal static string ExtensionPackageAttemptingToDeployContainsErrors {
            get {
                return ResourceManager.GetString("ExtensionPackageAttemptingToDeployContainsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The add-in package that you are attempting to deploy contains warnings. Kindly review them before continuing..
        /// </summary>
        internal static string ExtensionPackageAttemptingToDeployContainsWarnings {
            get {
                return ResourceManager.GetString("ExtensionPackageAttemptingToDeployContainsWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An add-in package with the same name already exists. Do you wish to overwrite it?.
        /// </summary>
        internal static string ExtensionWithSameNameAlreadyExist {
            get {
                return ResourceManager.GetString("ExtensionWithSameNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create and deploy application.
        /// </summary>
        internal static string FailedToCreateAndPublishApplication {
            get {
                return ResourceManager.GetString("FailedToCreateAndPublishApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string FeatureLayerMode {
            get {
                return ResourceManager.GetString("FeatureLayerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Retrieval.
        /// </summary>
        internal static string FeatureRetrieval {
            get {
                return ResourceManager.GetString("FeatureRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash animation is not defined on the target Builder toolbar button.
        /// </summary>
        internal static string FlashAnimationIsNotDefinedOnTargetBuilderToolbarButton {
            get {
                return ResourceManager.GetString("FlashAnimationIsNotDefinedOnTargetBuilderToolbarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following add-ons are available. Click.
        /// </summary>
        internal static string FollowingAddOnsAreAvailable {
            get {
                return ResourceManager.GetString("FollowingAddOnsAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string FollowingAddOnsAreAvailableHere {
            get {
                return ResourceManager.GetString("FollowingAddOnsAreAvailableHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to upload a new one from disk..
        /// </summary>
        internal static string FollowingAddOnsAreAvailableToUploadANewOne {
            get {
                return ResourceManager.GetString("FollowingAddOnsAreAvailableToUploadANewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were found..
        /// </summary>
        internal static string FollowingErrorsFound {
            get {
                return ResourceManager.GetString("FollowingErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the Application Builder in full screen mode.
        /// </summary>
        internal static string FullScreenDescription {
            get {
                return ResourceManager.GetString("FullScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Service:.
        /// </summary>
        internal static string GeometryService {
            get {
                return ResourceManager.GetString("GeometryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverage the spatial analytics of ArcGIS Server Geoprocessing Services..
        /// </summary>
        internal static string GettingStartedAddGPDescription {
            get {
                return ResourceManager.GetString("GettingStartedAddGPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Geoprocessing Services.
        /// </summary>
        internal static string GettingStartedAddGPTitle {
            get {
                return ResourceManager.GetString("GettingStartedAddGPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data from ArcGIS Online and ArcGIS Server..
        /// </summary>
        internal static string GettingStartedAddLayersDescription {
            get {
                return ResourceManager.GetString("GettingStartedAddLayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Operational Layers.
        /// </summary>
        internal static string GettingStartedAddLayersTitle {
            get {
                return ResourceManager.GetString("GettingStartedAddLayersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the application&apos;s functionality.
        /// </summary>
        internal static string GettingStartedAddToolsDescription {
            get {
                return ResourceManager.GetString("GettingStartedAddToolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tools.
        /// </summary>
        internal static string GettingStartedAddToolsTitle {
            get {
                return ResourceManager.GetString("GettingStartedAddToolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a basemap from ArcGIS Online, Bing Maps, or OpenStreetMap..
        /// </summary>
        internal static string GettingStartedBasemapDescription {
            get {
                return ResourceManager.GetString("GettingStartedBasemapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Basemap.
        /// </summary>
        internal static string GettingStartedBasemapTitle {
            get {
                return ResourceManager.GetString("GettingStartedBasemapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand the Viewer with your organization&apos;s logo..
        /// </summary>
        internal static string GettingStartedChooseLogoDescription {
            get {
                return ResourceManager.GetString("GettingStartedChooseLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Logo.
        /// </summary>
        internal static string GettingStartedChooseLogoTitle {
            get {
                return ResourceManager.GetString("GettingStartedChooseLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the look and feel of your Viewer..
        /// </summary>
        internal static string GettingStartedSelectLayoutDescription {
            get {
                return ResourceManager.GetString("GettingStartedSelectLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Layout.
        /// </summary>
        internal static string GettingStartedSelectLayoutTitle {
            get {
                return ResourceManager.GetString("GettingStartedSelectLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your application&apos;s title..
        /// </summary>
        internal static string GettingStartedSetTitleDescription {
            get {
                return ResourceManager.GetString("GettingStartedSetTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the Title.
        /// </summary>
        internal static string GettingStartedSetTitleTitle {
            get {
                return ResourceManager.GetString("GettingStartedSetTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To.
        /// </summary>
        internal static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string HelpLinks {
            get {
                return ResourceManager.GetString("HelpLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Getting Started Help.
        /// </summary>
        internal static string HideGettingStarted {
            get {
                return ResourceManager.GetString("HideGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the Application Builder&apos;s start page.
        /// </summary>
        internal static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon:.
        /// </summary>
        internal static string IconPrompt {
            get {
                return ResourceManager.GetString("IconPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        internal static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:.
        /// </summary>
        internal static string LabelPrompt {
            get {
                return ResourceManager.GetString("LabelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        internal static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        internal static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked to Web Map:.
        /// </summary>
        internal static string LinkedToWebMap {
            get {
                return ResourceManager.GetString("LinkedToWebMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string LinkToWebMap {
            get {
                return ResourceManager.GetString("LinkToWebMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Sites....
        /// </summary>
        internal static string LoadingSites {
            get {
                return ResourceManager.GetString("LoadingSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Add-Ins: Tools, Behaviors, Controls.
        /// </summary>
        internal static string ManageAddInsToolsBehaviorsControls {
            get {
                return ResourceManager.GetString("ManageAddInsToolsBehaviorsControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage application settings.
        /// </summary>
        internal static string ManageApplicationSettings {
            get {
                return ResourceManager.GetString("ManageApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Behaviors.
        /// </summary>
        internal static string ManageBehaviors {
            get {
                return ResourceManager.GetString("ManageBehaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable, disable, re-order, add, or delete the Viewer&apos;s behaviors.
        /// </summary>
        internal static string ManageBehaviorsDescription {
            get {
                return ResourceManager.GetString("ManageBehaviorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Extensions.
        /// </summary>
        internal static string ManageExtensions {
            get {
                return ResourceManager.GetString("ManageExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Personal Settings.
        /// </summary>
        internal static string ManagePersonalSettings {
            get {
                return ResourceManager.GetString("ManagePersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Toolbars.
        /// </summary>
        internal static string ManageToolbars {
            get {
                return ResourceManager.GetString("ManageToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, remove, move, and configure tools on the Viewer&apos;s toolbars.
        /// </summary>
        internal static string ManageToolbarsDescription {
            get {
                return ResourceManager.GetString("ManageToolbarsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map configuration for this application is linked to a web map.  To edit the map configuration, unlink the application from the web map..
        /// </summary>
        internal static string MapConfigurationUnavailable {
            get {
                return ResourceManager.GetString("MapConfigurationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Contents.
        /// </summary>
        internal static string MapContents {
            get {
                return ResourceManager.GetString("MapContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Size:.
        /// </summary>
        internal static string ModeCacheSizeLabel {
            get {
                return ResourceManager.GetString("ModeCacheSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Site Options.
        /// </summary>
        internal static string MoreSiteOptions {
            get {
                return ResourceManager.GetString("MoreSiteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move into the &apos;{0}&apos; group.
        /// </summary>
        internal static string MoveIntoGroup {
            get {
                return ResourceManager.GetString("MoveIntoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected group or control down the Toolbar tree.
        /// </summary>
        internal static string MoveSelectedGroupOrControlDownToolbarTree {
            get {
                return ResourceManager.GetString("MoveSelectedGroupOrControlDownToolbarTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected group or control up the Toolbar tree.
        /// </summary>
        internal static string MoveSelectedGroupOrControlUpToolbarTree {
            get {
                return ResourceManager.GetString("MoveSelectedGroupOrControlUpToolbarTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NamePrompt {
            get {
                return ResourceManager.GetString("NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Builder - New Application (not deployed).
        /// </summary>
        internal static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Link.
        /// </summary>
        internal static string NewLink {
            get {
                return ResourceManager.GetString("NewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string NewMap {
            get {
                return ResourceManager.GetString("NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found..
        /// </summary>
        internal static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not deployed).
        /// </summary>
        internal static string NotDeployed {
            get {
                return ResourceManager.GetString("NotDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Layer OnDemand Cache Size.
        /// </summary>
        internal static string OnDemandCacheSize {
            get {
                return ResourceManager.GetString("OnDemandCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the FeatureLayer OnDemand mode cache size (default= 1000).
        /// </summary>
        internal static string OnDemandCacheSizeDescription {
            get {
                return ResourceManager.GetString("OnDemandCacheSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureLayer OnDemand Mode.
        /// </summary>
        internal static string OnDemandRadio {
            get {
                return ResourceManager.GetString("OnDemandRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the query mode for the layer to be OnDemand (FeatureLayers only).
        /// </summary>
        internal static string OnDemandRadioDescription {
            get {
                return ResourceManager.GetString("OnDemandRadioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Web Map from ArcGIS.com.
        /// </summary>
        internal static string OpenWebMapFromArcGISCom {
            get {
                return ResourceManager.GetString("OpenWebMapFromArcGISCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Settings.
        /// </summary>
        internal static string PersonalSettings {
            get {
                return ResourceManager.GetString("PersonalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy:.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy application.
        /// </summary>
        internal static string PublishApplication {
            get {
                return ResourceManager.GetString("PublishApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy the current Viewer to a new website.
        /// </summary>
        internal static string PublishDescription {
            get {
                return ResourceManager.GetString("PublishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the currently selected layer.
        /// </summary>
        internal static string RefreshCurrentlySelectedLayer {
            get {
                return ResourceManager.GetString("RefreshCurrentlySelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        internal static string RemoveLink {
            get {
                return ResourceManager.GetString("RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the currently selected layer.
        /// </summary>
        internal static string RemovesCurrentlySelectedLayer {
            get {
                return ResourceManager.GetString("RemovesCurrentlySelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected group or control.
        /// </summary>
        internal static string RemoveSelectedGroupOrControl {
            get {
                return ResourceManager.GetString("RemoveSelectedGroupOrControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the currently selected layer.
        /// </summary>
        internal static string RenameCurrentlySelectedLayer {
            get {
                return ResourceManager.GetString("RenameCurrentlySelectedLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Theme.
        /// </summary>
        internal static string ResetTheme {
            get {
                return ResourceManager.GetString("ResetTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the Viewer&apos;s theme colors to their default values.
        /// </summary>
        internal static string ResetThemeDescription {
            get {
                return ResourceManager.GetString("ResetThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to previous screen.
        /// </summary>
        internal static string ReturnToPreviousScreen {
            get {
                return ResourceManager.GetString("ReturnToPreviousScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a toolbar or root level node of a toolbar to add a Group..
        /// </summary>
        internal static string RootLevelToAddGroup {
            get {
                return ResourceManager.GetString("RootLevelToAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current Viewer.
        /// </summary>
        internal static string SaveDescription {
            get {
                return ResourceManager.GetString("SaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a tool to add:.
        /// </summary>
        internal static string SelectAToolToAdd {
            get {
                return ResourceManager.GetString("SelectAToolToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Outline.
        /// </summary>
        internal static string SelectionOutline {
            get {
                return ResourceManager.GetString("SelectionOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tool....
        /// </summary>
        internal static string SelectTheTool {
            get {
                return ResourceManager.GetString("SelectTheTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string SendBackward {
            get {
                return ResourceManager.GetString("SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the layer&apos;s display order one position closer to the bottom of the map.
        /// </summary>
        internal static string SendsCurrentlySelectedLayerBackward {
            get {
                return ResourceManager.GetString("SendsCurrentlySelectedLayerBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Separator&gt;.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Details.
        /// </summary>
        internal static string ServiceDetails {
            get {
                return ResourceManager.GetString("ServiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Getting Started Help.
        /// </summary>
        internal static string ShowGettingStarted {
            get {
                return ResourceManager.GetString("ShowGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Me.
        /// </summary>
        internal static string ShowMe {
            get {
                return ResourceManager.GetString("ShowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Copy Failed.
        /// </summary>
        internal static string SiteCopyFailed {
            get {
                return ResourceManager.GetString("SiteCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Deployment Failed.
        /// </summary>
        internal static string SiteDeploymentFailed {
            get {
                return ResourceManager.GetString("SiteDeploymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureLayer SnapShot Mode.
        /// </summary>
        internal static string SnapShotRadio {
            get {
                return ResourceManager.GetString("SnapShotRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the query mode for the layer to be SnapShot (FeatureLayers only).
        /// </summary>
        internal static string SnapShotRadioDescription {
            get {
                return ResourceManager.GetString("SnapShotRadioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the layout of your application.
        /// </summary>
        internal static string SpecifyLayoutOfYourApplication {
            get {
                return ResourceManager.GetString("SpecifyLayoutOfYourApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the tool&apos;s properties.
        /// </summary>
        internal static string SpecifyToolProperties {
            get {
                return ResourceManager.GetString("SpecifyToolProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with existing.
        /// </summary>
        internal static string StartWithExistingMap {
            get {
                return ResourceManager.GetString("StartWithExistingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Colors.
        /// </summary>
        internal static string ThemeColors {
            get {
                return ResourceManager.GetString("ThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title and Links.
        /// </summary>
        internal static string TitleAndLinks {
            get {
                return ResourceManager.GetString("TitleAndLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TitlePrompt {
            get {
                return ResourceManager.GetString("TitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the browse panel.  Browse allows you to view the contents of an ArcGIS Server or Spatial Data Service endpoint and add layers to the map..
        /// </summary>
        internal static string ToggleBrowseDescription {
            get {
                return ResourceManager.GetString("ToggleBrowseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide a list of the map&apos;s contents.
        /// </summary>
        internal static string ToggleMapContentsDescription {
            get {
                return ResourceManager.GetString("ToggleMapContentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the search panel.  Search allows you to search for places, search ArcGIS.com for content, or search the web for ArcGIS Server services..
        /// </summary>
        internal static string ToggleSearchDescription {
            get {
                return ResourceManager.GetString("ToggleSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the attribute table for the currently selected layer.
        /// </summary>
        internal static string ToggleTableDescription {
            get {
                return ResourceManager.GetString("ToggleTableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Toolbar.
        /// </summary>
        internal static string ToggleToolbar {
            get {
                return ResourceManager.GetString("ToggleToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide Application Builder&apos;s toolbar.
        /// </summary>
        internal static string ToggleToolbarDescription {
            get {
                return ResourceManager.GetString("ToggleToolbarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar:.
        /// </summary>
        internal static string ToolbarPrompt {
            get {
                return ResourceManager.GetString("ToolbarPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip:.
        /// </summary>
        internal static string TooltipPrompt {
            get {
                return ResourceManager.GetString("TooltipPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Getting Started.
        /// </summary>
        internal static string TutorialModeDisable {
            get {
                return ResourceManager.GetString("TutorialModeDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Getting Started.
        /// </summary>
        internal static string TutorialModeEnable {
            get {
                return ResourceManager.GetString("TutorialModeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TypePrompt {
            get {
                return ResourceManager.GetString("TypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deploy application..
        /// </summary>
        internal static string UnableToDeployApplication {
            get {
                return ResourceManager.GetString("UnableToDeployApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save application changes..
        /// </summary>
        internal static string UnableToSaveApplicationChanges {
            get {
                return ResourceManager.GetString("UnableToSaveApplicationChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink.
        /// </summary>
        internal static string UnlinkFromWebMap {
            get {
                return ResourceManager.GetString("UnlinkFromWebMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade this Viewer application to the current version.
        /// </summary>
        internal static string UpgradeSite {
            get {
                return ResourceManager.GetString("UpgradeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrading application....
        /// </summary>
        internal static string UpgradingApplication {
            get {
                return ResourceManager.GetString("UpgradingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Add-In Packages.
        /// </summary>
        internal static string UploadAddInPackages {
            get {
                return ResourceManager.GetString("UploadAddInPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Add-Ins.
        /// </summary>
        internal static string UploadAddIns {
            get {
                return ResourceManager.GetString("UploadAddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnDemand.
        /// </summary>
        internal static string UseOnDemandMode {
            get {
                return ResourceManager.GetString("UseOnDemandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnapShot.
        /// </summary>
        internal static string UseSnapShotMode {
            get {
                return ResourceManager.GetString("UseSnapShotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer project.
        /// </summary>
        internal static string ViewerProject {
            get {
                return ResourceManager.GetString("ViewerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View information about the selected layer&apos;s data source.
        /// </summary>
        internal static string ViewInformationAboutSelectedLayerDatasource {
            get {
                return ResourceManager.GetString("ViewInformationAboutSelectedLayerDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webmap.
        /// </summary>
        internal static string WebMap {
            get {
                return ResourceManager.GetString("WebMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArcGIS Application Builder is a web application that allows you to create and edit Viewer applications in a real-time and fully interactive fashion.  The Application Builder and Viewer applications are built using the ArcGIS API for Silverlight..
        /// </summary>
        internal static string WelcomeMsgParagraph1 {
            get {
                return ResourceManager.GetString("WelcomeMsgParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started creating a Viewer, click the Create New Application button below.  The Viewer you are configuring will be shown below the Application Builder&apos;s toolbar. You can configure your Viewer&apos;s basemap, layers, tools, title, logo, colors, and more using the tools on the toolbar.  Once you have configured your Viewer, click the Deploy button to deploy it to a new website..
        /// </summary>
        internal static string WelcomeMsgParagraph2 {
            get {
                return ResourceManager.GetString("WelcomeMsgParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to the currently selected layer.
        /// </summary>
        internal static string ZoomToCurrentlySelectedLayer {
            get {
                return ResourceManager.GetString("ZoomToCurrentlySelectedLayer", resourceCulture);
            }
        }
    }
}
