/*
(c) Copyright ESRI.
This source is subject to the Microsoft Public License (Ms-PL).
Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
All other rights reserved.
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESRI.ArcGIS.Mapping.GP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESRI.ArcGIS.Mapping.GP.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}layers to map.
        /// </summary>
        internal static string AddLayersToMap {
            get {
                return ResourceManager.GetString("AddLayersToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to a geoprocessing service.
        /// </summary>
        internal static string BrowseToGP {
            get {
                return ResourceManager.GetString("BrowseToGP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to a task....
        /// </summary>
        internal static string BrowseToTask {
            get {
                return ResourceManager.GetString("BrowseToTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting a layer from the map.
        /// </summary>
        internal static string BySelectingLayerFromMap {
            get {
                return ResourceManager.GetString("BySelectingLayerFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all fields.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Geoprocessing.
        /// </summary>
        internal static string ConfigureGeoprocessing {
            get {
                return ResourceManager.GetString("ConfigureGeoprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure input parameters.
        /// </summary>
        internal static string ConfigureInputHeading {
            get {
                return ResourceManager.GetString("ConfigureInputHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the input parameters for the geoprocessing task.
        /// </summary>
        internal static string ConfigureInputParameterForGeoprocessingTask {
            get {
                return ResourceManager.GetString("ConfigureInputParameterForGeoprocessingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure output parameters.
        /// </summary>
        internal static string ConfigureOutputHeading {
            get {
                return ResourceManager.GetString("ConfigureOutputHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the output parameters for the geoprocessing task.
        /// </summary>
        internal static string ConfigureOutputParameterForGeoprocessingTask {
            get {
                return ResourceManager.GetString("ConfigureOutputParameterForGeoprocessingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure pop-up field aliases and visibility.
        /// </summary>
        internal static string ConfigurePopupFieldAliasesAndVisibility {
            get {
                return ResourceManager.GetString("ConfigurePopupFieldAliasesAndVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure pop-ups.
        /// </summary>
        internal static string ConfigurePopups {
            get {
                return ResourceManager.GetString("ConfigurePopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure renderer.
        /// </summary>
        internal static string ConfigureRenderer {
            get {
                return ResourceManager.GetString("ConfigureRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the selected geoprocessing task.
        /// </summary>
        internal static string ConfigureSelectedGPTask {
            get {
                return ResourceManager.GetString("ConfigureSelectedGPTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure title and layer order.
        /// </summary>
        internal static string ConfigureTitleAndLayerOrder {
            get {
                return ResourceManager.GetString("ConfigureTitleAndLayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring.
        /// </summary>
        internal static string Configuring {
            get {
                return ResourceManager.GetString("Configuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Degrees.
        /// </summary>
        internal static string DecimalDegrees {
            get {
                return ResourceManager.GetString("DecimalDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimeters.
        /// </summary>
        internal static string Decimeters {
            get {
                return ResourceManager.GetString("Decimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw line.
        /// </summary>
        internal static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw point.
        /// </summary>
        internal static string DrawPoint {
            get {
                return ResourceManager.GetString("DrawPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw polygon.
        /// </summary>
        internal static string DrawPolygon {
            get {
                return ResourceManager.GetString("DrawPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service returned an empty response.
        /// </summary>
        internal static string EmptyResponse {
            get {
                return ResourceManager.GetString("EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter url for file.
        /// </summary>
        internal static string EnterUrlForFile {
            get {
                return ResourceManager.GetString("EnterUrlForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter url for raster data.
        /// </summary>
        internal static string EnterUrlForRasterData {
            get {
                return ResourceManager.GetString("EnterUrlForRasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter url for raster data layer.
        /// </summary>
        internal static string EnterUrlForRasterDataLayer {
            get {
                return ResourceManager.GetString("EnterUrlForRasterDataLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter url for record set.
        /// </summary>
        internal static string EnterUrlForRecordset {
            get {
                return ResourceManager.GetString("EnterUrlForRecordset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppendProperty called outside of an object.
        /// </summary>
        internal static string ExceptionAppendPropertyCalledOutsideOfAnObject {
            get {
                return ResourceManager.GetString("ExceptionAppendPropertyCalledOutsideOfAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Escape.
        /// </summary>
        internal static string ExceptionBadEscape {
            get {
                return ResourceManager.GetString("ExceptionBadEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converters.
        /// </summary>
        internal static string ExceptionConverters {
            get {
                return ResourceManager.GetString("ExceptionConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndArray called with no matching StartArray.
        /// </summary>
        internal static string ExceptionEndArrayCalledwithNoMatchingStartArray {
            get {
                return ResourceManager.GetString("ExceptionEndArrayCalledwithNoMatchingStartArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndArrayIndented called with no matching StartArray.
        /// </summary>
        internal static string ExceptionEndArrayIndentedCalledwithNoMatchingStartArray {
            get {
                return ResourceManager.GetString("ExceptionEndArrayIndentedCalledwithNoMatchingStartArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndObject called with no matching StartObject.
        /// </summary>
        internal static string ExceptionEndObjectCalledWithNoMatchingStartObject {
            get {
                return ResourceManager.GetString("ExceptionEndObjectCalledWithNoMatchingStartObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndObjectIndented called with no matching StartObject.
        /// </summary>
        internal static string ExceptionEndObjectIndentedCalledWithNoMatchingStartObject {
            get {
                return ResourceManager.GetString("ExceptionEndObjectIndentedCalledWithNoMatchingStartObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        internal static string ExceptionInput {
            get {
                return ResourceManager.GetString("ExceptionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartProperty called outside of an object.
        /// </summary>
        internal static string ExceptionStartPropertycalledOutsideOfAnObject {
            get {
                return ResourceManager.GetString("ExceptionStartPropertycalledOutsideOfAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteProperty called outside of an object.
        /// </summary>
        internal static string ExceptionWritePropertyCalledOutsideOfAnObject {
            get {
                return ResourceManager.GetString("ExceptionWritePropertyCalledOutsideOfAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        internal static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        internal static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load task information..
        /// </summary>
        internal static string FailedToLoadTaskInformation {
            get {
                return ResourceManager.GetString("FailedToLoadTaskInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field information is not known..
        /// </summary>
        internal static string FieldInformationIsNotKnown {
            get {
                return ResourceManager.GetString("FieldInformationIsNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the map&apos;s extent.
        /// </summary>
        internal static string FromMapExtent {
            get {
                return ResourceManager.GetString("FromMapExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type is not known..
        /// </summary>
        internal static string GeometryTypeIsNotKnown {
            get {
                return ResourceManager.GetString("GeometryTypeIsNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing has not been configured..
        /// </summary>
        internal static string GeoprocessingHasNotBeenconfigured {
            get {
                return ResourceManager.GetString("GeoprocessingHasNotBeenconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting results....
        /// </summary>
        internal static string GettingResults {
            get {
                return ResourceManager.GetString("GettingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL to an ArcGIS Server or select a server from the drop-down.  Then select the geoprocessing task to configure and click Next..
        /// </summary>
        internal static string GPBrowseInstructions {
            get {
                return ResourceManager.GetString("GPBrowseInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL to an ArcGIS Server containing geoprocessing services.
        /// </summary>
        internal static string GPBrowseTooltip {
            get {
                return ResourceManager.GetString("GPBrowseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Server or GP Task URL.
        /// </summary>
        internal static string GPBrowseWatermark {
            get {
                return ResourceManager.GetString("GPBrowseWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header:.
        /// </summary>
        internal static string HeaderPrompt {
            get {
                return ResourceManager.GetString("HeaderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about this geoprocessing tool..
        /// </summary>
        internal static string InformationAboutThisGeoprocessingTool {
            get {
                return ResourceManager.GetString("InformationAboutThisGeoprocessingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactively.
        /// </summary>
        internal static string Interactively {
            get {
                return ResourceManager.GetString("Interactively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geoprocessing job has failed.
        /// </summary>
        internal static string JobFailed {
            get {
                return ResourceManager.GetString("JobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value:.
        /// </summary>
        internal static string LabelDefaultValue {
            get {
                return ResourceManager.GetString("LabelDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string LabelFormat {
            get {
                return ResourceManager.GetString("LabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Tooltip:.
        /// </summary>
        internal static string LabelFormatTooltip {
            get {
                return ResourceManager.GetString("LabelFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input features:.
        /// </summary>
        internal static string LabelInputFeatures {
            get {
                return ResourceManager.GetString("LabelInputFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:.
        /// </summary>
        internal static string LabelLabel {
            get {
                return ResourceManager.GetString("LabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer name:.
        /// </summary>
        internal static string LabelLayerName {
            get {
                return ResourceManager.GetString("LabelLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop-Ups:.
        /// </summary>
        internal static string LabelPopUps {
            get {
                return ResourceManager.GetString("LabelPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderer:.
        /// </summary>
        internal static string LabelRenderer {
            get {
                return ResourceManager.GetString("LabelRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show parameter:.
        /// </summary>
        internal static string LabelShowParameter {
            get {
                return ResourceManager.GetString("LabelShowParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip:.
        /// </summary>
        internal static string LabelTooltip {
            get {
                return ResourceManager.GetString("LabelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency:.
        /// </summary>
        internal static string LabelTransparency {
            get {
                return ResourceManager.GetString("LabelTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        internal static string LabelUrl {
            get {
                return ResourceManager.GetString("LabelUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Order:.
        /// </summary>
        internal static string LayerOrder {
            get {
                return ResourceManager.GetString("LayerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        internal static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Miles.
        /// </summary>
        internal static string NauticalMiles {
            get {
                return ResourceManager.GetString("NauticalMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} layers available.
        /// </summary>
        internal static string NoLayersAvailable {
            get {
                return ResourceManager.GetString("NoLayersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Only url output is supported for record sets&gt;.
        /// </summary>
        internal static string OnlyUrlOutputIsSupportedForRecordsets {
            get {
                return ResourceManager.GetString("OnlyUrlOutputIsSupportedForRecordsets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange Stickpin.
        /// </summary>
        internal static string OrangeStickpin {
            get {
                return ResourceManager.GetString("OrangeStickpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Layers.
        /// </summary>
        internal static string OrderLayers {
            get {
                return ResourceManager.GetString("OrderLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save web part by clicking OK or Apply..
        /// </summary>
        internal static string SaveWebpartByClickingOK {
            get {
                return ResourceManager.GetString("SaveWebpartByClickingOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all fields.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select geoprocessing task.
        /// </summary>
        internal static string SelectGeoprocessingTask {
            get {
                return ResourceManager.GetString("SelectGeoprocessingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the order of the layers that will be created by the geoprocessing task.
        /// </summary>
        internal static string SpecifyOrderOfLayersCreatedByGeoprocessingTask {
            get {
                return ResourceManager.GetString("SpecifyOrderOfLayersCreatedByGeoprocessingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        internal static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        internal static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected GP Task:.
        /// </summary>
        internal static string TaskPrompt {
            get {
                return ResourceManager.GetString("TaskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Title:.
        /// </summary>
        internal static string TitlePrompt {
            get {
                return ResourceManager.GetString("TitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred accessing the geoprocessing service..
        /// </summary>
        internal static string UnexpectedServiceAccessError {
            get {
                return ResourceManager.GetString("UnexpectedServiceAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown geometry type.
        /// </summary>
        internal static string UnknownGeometryType {
            get {
                return ResourceManager.GetString("UnknownGeometryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Zoom to the extent you&apos;d like to use as input &gt;.
        /// </summary>
        internal static string ZoomToExtentInput {
            get {
                return ResourceManager.GetString("ZoomToExtentInput", resourceCulture);
            }
        }
    }
}
